#!/usr/bin/env bun

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"
import solidPlugin from "@opentui/solid/bun-plugin"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import { Script } from "@opencode-ai/script"
import pkg from "../package.json"

// Fix for Bun snap environment: ensure BUN_INSTALL points to a writable local path.
// We must set this BEFORE Bun's native compiler starts. If we are in a snap and it's not set,
// we re-spawn the process with the correct environment.
if (process.env.SNAP && process.env.HOME && !process.env.BUN_INSTALL?.startsWith(process.env.HOME)) {
  const localBun = path.join(process.env.HOME, ".bun")
  const env = { ...process.env, BUN_INSTALL: localBun }
  const proc = Bun.spawnSync([process.argv[0], ...process.argv.slice(1)], {
    env,
    stdio: ["inherit", "inherit", "inherit"],
  })
  process.exit(proc.exitCode)
}

async function prefetch(baseTarget: string) {
  const version = process.versions.bun
  const isWin = baseTarget.includes("windows")
  const os = isWin ? "windows" : baseTarget.split("-")[0]
  let arch = baseTarget.split("-")[1]
  if (arch === "arm64") arch = "aarch64"
  const baseline = baseTarget.includes("baseline") ? "-baseline" : ""
  const abi = baseTarget.includes("musl") ? "-musl" : ""
  const releaseName = `bun-${os}-${arch}${baseline}${abi}`

  const bunInstall = process.env.BUN_INSTALL || path.join(process.env.HOME || "/home/heidi", ".bun")
  const cacheDir = path.join(bunInstall, "install/cache", `bun-v${version}`)
  const targetDir = path.join(cacheDir, releaseName)
  const binaryName = isWin ? "bun.exe" : "bun"
  const binaryPath = path.join(targetDir, binaryName)

  if (fs.existsSync(binaryPath)) {
    console.log(`  [cache] ${releaseName} found at ${binaryPath}`)
    return
  }

  console.log(`  [prefetch] ${releaseName} starting...`)
  const url = `https://github.com/oven-sh/bun/releases/download/bun-v${version}/${releaseName}.zip`
  try {
    const res = await fetch(url)
    if (!res.ok) {
      throw new Error(`HTTP ${res.status} when fetching ${url}`)
    }
    const buffer = await res.arrayBuffer()
    const zipPath = path.join(process.env.TMPDIR || "/tmp", `${releaseName}.zip`)
    await Bun.write(zipPath, buffer)

    if (!fs.existsSync(cacheDir)) fs.mkdirSync(cacheDir, { recursive: true })

    const proc = Bun.spawnSync(["python3", "-m", "zipfile", "-e", zipPath, cacheDir])
    if (!proc.success) {
      throw new Error(`Failed to extract ${releaseName}: ${proc.stderr.toString()}`)
    }
    
    // Set executable bit for the binary
    if (fs.existsSync(binaryPath)) {
      fs.chmodSync(binaryPath, 0o755)
      console.log(`  [prefetch] ${releaseName} successfully cached`)
    } else {
      console.warn(`  [prefetch] binary not found after extraction at ${binaryPath}`)
    }

    fs.unlinkSync(zipPath)
  } catch (err: any) {
    console.warn(`  [prefetch] failed for ${releaseName}: ${err.message}. Bun will try its internal downloader.`)
  }
}

const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)
console.log("Generated models-snapshot.ts")

// Load migrations from migration directories
const migrationDirs = (
  await fs.promises.readdir(path.join(dir, "migration"), {
    withFileTypes: true,
  })
)
  .filter((entry) => entry.isDirectory() && /^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(dir, "migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
          Number(match[1]),
          Number(match[2]) - 1,
          Number(match[3]),
          Number(match[4]),
          Number(match[5]),
          Number(match[6]),
        )
      : 0
    return { sql, timestamp, name }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
  {
    os: "linux",
    arch: "x64",
  },
  {
    os: "linux",
    arch: "x64",
    avx2: false,
  },
  {
    os: "win32",
    arch: "x64",
  },
  {
    os: "win32",
    arch: "x64",
    avx2: false,
  },
]

const targets = singleFlag
  ? allTargets.filter((item) => {
      if (item.os !== process.platform || item.arch !== process.arch) {
        return false
      }

      // When building for the current platform, prefer a single native binary by default.
      // Baseline binaries require additional Bun artifacts and can be flaky to download.
      if (item.avx2 === false) {
        return baselineFlag
      }

      // also skip abi-specific builds for the same reason
      if (item.abi !== undefined) {
        return false
      }

      return true
    })
  : allTargets

await $`rm -rf dist`

const binaries: Record<string, string> = {}
if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}
for (const item of targets) {
  const name = [
    pkg.name,
    // changing to win32 flags npm for some reason
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")
  
  const baseTarget = name.replace(pkg.name + "-", "")
  await prefetch(baseTarget)

  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}/bin`

  const localPath = path.resolve(dir, "node_modules/@opentui/core/parser.worker.js")
  const rootPath = path.resolve(dir, "../../node_modules/@opentui/core/parser.worker.js")
  const parserWorker = fs.realpathSync(fs.existsSync(localPath) ? localPath : rootPath)
  const workerPath = "./src/cli/cmd/tui/worker.ts"

  // Use platform-specific bunfs root path based on target OS
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

  await Bun.build({
    tsconfig: "./tsconfig.json",
    plugins: [
      {
        name: "zod-bug-workaround",
        setup(build) {
          build.onLoad({ filter: /zod.*\.js$/ }, async (args) => {
            let contents = await fs.promises.readFile(args.path, "utf8")
            if (contents.match(/import \* as util from/)) {
              contents = contents.replace(/import \* as util from/g, 'import * as _zodUtil from');
              contents += "\nvar util = _zodUtil;\n";
            }
            return {
              contents,
              loader: "js",
            }
          })
        },
      },
      solidPlugin,
      {
        name: "resolve-js-to-ts",
        setup(build) {
          build.onResolve({ filter: /\.js$/ }, (args) => {
            if (args.importer && args.path.startsWith(".")) {
              const dir = path.dirname(args.importer)
              const js = path.resolve(dir, args.path)
              if (!fs.existsSync(js)) {
                const ts = js.replace(/\.js$/, ".ts")
                if (fs.existsSync(ts)) return { path: ts }
              }
            }
            return undefined
          })
        },
      },
    ],
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace(pkg.name, "bun") as any,
      outfile: `dist/${name}/bin/opencode`,
      execArgv: [`--user-agent=opencode/${Script.version}`, "--use-system-ca", "--"],
      windows: {},
    },
    entrypoints: ["./src/index.ts", parserWorker, workerPath],
    external: ["playwright-core"],
    define: {
      OPENCODE_VERSION: `'${Script.version}'`,
      OPENCODE_MIGRATIONS: JSON.stringify(migrations),
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      OPENCODE_WORKER_PATH: workerPath,
      OPENCODE_CHANNEL: `'${Script.channel}'`,
      OPENCODE_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
    },
  })



  await $`rm -rf ./dist/${name}/bin/tui`
  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  binaries[name] = Script.version
}

if (Script.release) {
  for (const key of Object.keys(binaries)) {
    if (key.includes("linux")) {
      await $`tar -czf ../../${key}.tar.gz *`.cwd(`dist/${key}/bin`)
    } else {
      await $`zip -r ../../${key}.zip *`.cwd(`dist/${key}/bin`)
    }
  }
  await $`gh release upload v${Script.version} ./dist/*.zip ./dist/*.tar.gz --clobber --repo ${process.env.GH_REPO}`
}

export { binaries }
